I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4918, in script
    Ashñey "Call the detective."
Exception: Sayer 'Ashñey' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4918, in script
    Ashñey "Call the detective."
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Ashñey' is not defined.

Windows-10-10.0.18362
Ren'Py 7.4.4.1439
The Graves Case 0.2
Wed Mar 13 21:51:35 2024
